version: "3"
services:
  bld:
    image: quay.io/cloudian/centos-ssh:7.7.1908-ant
    hostname: bld1
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
    dns_search:
      - localdomain
    ports:
      - "3022:22"
    volumes:
      - ~/work:/home/worker/work
      - ~/.ssh:/home/worker/.ssh
      - ~/.ivy2:/home/worker/.ivy2
      - ./resolv.conf:/etc/resolv.conf
    networks:
      net1:
        ipv4_address: 10.1.1.2
networks:
  net1:
    ipam:
      config:
        - subnet: 10.1.1.0/24
