version: "2"
services:
  bld:
    image: quay.io/cloudian/centos-ssh:ant
    hostname: bld1
    privileged: true
    dns:
      - 127.0.0.1
      - 8.8.8.8
    dns_search:
      - localdomain
    volumes:
      - ~/work:/home/worker/work
    networks:
      net1:
        ipv4_address: 10.1.1.2
networks:
  net1:
    ipam:
      config:
        - subnet: 10.1.1.0/24
          ip_range: 10.1.1.0/24
          gateway: 10.1.1.1
